# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import pipemesh_pb2 as pipemesh__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in pipemesh_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PipeMeshStub:
    """---------------------------------------------------------------------------
    Outbound: a caller drives the runtime (§26.4)
    ---------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartExecution = channel.unary_unary(
                '/pipemesh.v1.PipeMesh/StartExecution',
                request_serializer=pipemesh__pb2.StartExecutionRequest.SerializeToString,
                response_deserializer=pipemesh__pb2.ExecutionHandle.FromString,
                _registered_method=True)
        self.ProcessMessage = channel.unary_unary(
                '/pipemesh.v1.PipeMesh/ProcessMessage',
                request_serializer=pipemesh__pb2.ProcessMessageRequest.SerializeToString,
                response_deserializer=pipemesh__pb2.ExecutionHandle.FromString,
                _registered_method=True)
        self.SubmitApproval = channel.unary_unary(
                '/pipemesh.v1.PipeMesh/SubmitApproval',
                request_serializer=pipemesh__pb2.SubmitApprovalRequest.SerializeToString,
                response_deserializer=pipemesh__pb2.ExecutionHandle.FromString,
                _registered_method=True)
        self.GetExecution = channel.unary_unary(
                '/pipemesh.v1.PipeMesh/GetExecution',
                request_serializer=pipemesh__pb2.GetExecutionRequest.SerializeToString,
                response_deserializer=pipemesh__pb2.ExecutionSnapshot.FromString,
                _registered_method=True)
        self.WatchExecution = channel.unary_stream(
                '/pipemesh.v1.PipeMesh/WatchExecution',
                request_serializer=pipemesh__pb2.WatchExecutionRequest.SerializeToString,
                response_deserializer=pipemesh__pb2.ExecutionUpdate.FromString,
                _registered_method=True)
        self.PublishEvent = channel.unary_unary(
                '/pipemesh.v1.PipeMesh/PublishEvent',
                request_serializer=pipemesh__pb2.PublishEventRequest.SerializeToString,
                response_deserializer=pipemesh__pb2.PublishEventResponse.FromString,
                _registered_method=True)


class PipeMeshServicer:
    """---------------------------------------------------------------------------
    Outbound: a caller drives the runtime (§26.4)
    ---------------------------------------------------------------------------

    """

    def StartExecution(self, request, context):
        """Runs a named workflow. The SDK's execute().
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessMessage(self, request, context):
        """Resolves intent first, then runs whatever workflow it chose. The SDK's
        process(). Intent selects a workflow; it does not run one (§19, §20).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitApproval(self, request, context):
        """Lets a suspended execution continue. Delivering the same decision twice is
        not an error and does not advance the execution twice.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExecution(self, request, context):
        """Where an execution stands, right now.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchExecution(self, request, context):
        """The same execution, observed as it happens. The SDK's stream(); this is not
        a third execution model, it is a view of one that is already running (§30).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishEvent(self, request, context):
        """Wakes whatever is waiting for this event (§9.7). An approval knows which
        execution it belongs to; an event does not — a payment service knows an
        order number and nothing about executions — so the match is made on a key
        recorded when the execution suspended.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PipeMeshServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartExecution': grpc.unary_unary_rpc_method_handler(
                    servicer.StartExecution,
                    request_deserializer=pipemesh__pb2.StartExecutionRequest.FromString,
                    response_serializer=pipemesh__pb2.ExecutionHandle.SerializeToString,
            ),
            'ProcessMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessMessage,
                    request_deserializer=pipemesh__pb2.ProcessMessageRequest.FromString,
                    response_serializer=pipemesh__pb2.ExecutionHandle.SerializeToString,
            ),
            'SubmitApproval': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitApproval,
                    request_deserializer=pipemesh__pb2.SubmitApprovalRequest.FromString,
                    response_serializer=pipemesh__pb2.ExecutionHandle.SerializeToString,
            ),
            'GetExecution': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExecution,
                    request_deserializer=pipemesh__pb2.GetExecutionRequest.FromString,
                    response_serializer=pipemesh__pb2.ExecutionSnapshot.SerializeToString,
            ),
            'WatchExecution': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchExecution,
                    request_deserializer=pipemesh__pb2.WatchExecutionRequest.FromString,
                    response_serializer=pipemesh__pb2.ExecutionUpdate.SerializeToString,
            ),
            'PublishEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishEvent,
                    request_deserializer=pipemesh__pb2.PublishEventRequest.FromString,
                    response_serializer=pipemesh__pb2.PublishEventResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pipemesh.v1.PipeMesh', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pipemesh.v1.PipeMesh', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PipeMesh:
    """---------------------------------------------------------------------------
    Outbound: a caller drives the runtime (§26.4)
    ---------------------------------------------------------------------------

    """

    @staticmethod
    def StartExecution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pipemesh.v1.PipeMesh/StartExecution',
            pipemesh__pb2.StartExecutionRequest.SerializeToString,
            pipemesh__pb2.ExecutionHandle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pipemesh.v1.PipeMesh/ProcessMessage',
            pipemesh__pb2.ProcessMessageRequest.SerializeToString,
            pipemesh__pb2.ExecutionHandle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitApproval(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pipemesh.v1.PipeMesh/SubmitApproval',
            pipemesh__pb2.SubmitApprovalRequest.SerializeToString,
            pipemesh__pb2.ExecutionHandle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetExecution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pipemesh.v1.PipeMesh/GetExecution',
            pipemesh__pb2.GetExecutionRequest.SerializeToString,
            pipemesh__pb2.ExecutionSnapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchExecution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/pipemesh.v1.PipeMesh/WatchExecution',
            pipemesh__pb2.WatchExecutionRequest.SerializeToString,
            pipemesh__pb2.ExecutionUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pipemesh.v1.PipeMesh/PublishEvent',
            pipemesh__pb2.PublishEventRequest.SerializeToString,
            pipemesh__pb2.PublishEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CapabilityWorkerStub:
    """---------------------------------------------------------------------------
    Inbound: the runtime invokes work that lives in an SDK (§26.1)

    A worker opens the stream and the runtime pushes invocations down it, so a
    worker needs no inbound address, certificate or firewall exception.
    ---------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.stream_stream(
                '/pipemesh.v1.CapabilityWorker/Connect',
                request_serializer=pipemesh__pb2.WorkerMessage.SerializeToString,
                response_deserializer=pipemesh__pb2.CapabilityInvocation.FromString,
                _registered_method=True)


class CapabilityWorkerServicer:
    """---------------------------------------------------------------------------
    Inbound: the runtime invokes work that lives in an SDK (§26.1)

    A worker opens the stream and the runtime pushes invocations down it, so a
    worker needs no inbound address, certificate or firewall exception.
    ---------------------------------------------------------------------------

    """

    def Connect(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CapabilityWorkerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connect': grpc.stream_stream_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=pipemesh__pb2.WorkerMessage.FromString,
                    response_serializer=pipemesh__pb2.CapabilityInvocation.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pipemesh.v1.CapabilityWorker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pipemesh.v1.CapabilityWorker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CapabilityWorker:
    """---------------------------------------------------------------------------
    Inbound: the runtime invokes work that lives in an SDK (§26.1)

    A worker opens the stream and the runtime pushes invocations down it, so a
    worker needs no inbound address, certificate or firewall exception.
    ---------------------------------------------------------------------------

    """

    @staticmethod
    def Connect(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/pipemesh.v1.CapabilityWorker/Connect',
            pipemesh__pb2.WorkerMessage.SerializeToString,
            pipemesh__pb2.CapabilityInvocation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
